/*Given the inputs P (string) and K then O is generated by replicating the P, K times.
 Check the divisibility of Q by 11 */
#include<stdio.h>
struct divisible
{
	char *p; //p is input char array
	int k; //k is no of times the number should be repeated to obtain Q
}d[]={
			{"1",1},
			{"1",2},
			{"123",3},
			{"123",2},
			{"11",9},
			{"11",10},
			{"121",7},
			{"121",6},
			{"12345678912345",3},
			{"12345678912345",4}
		};
void testCases();
int computeLength(char *str);
void divisibility(struct divisible *stpr);

int main(void)
{
	testCases();
	return 0;
}

void testCases()
{
		int noOfElements=sizeof(d)/sizeof(d[0]);
		for(int index=0;index<noOfElements;index++)
			divisibility(&d[index]);
}

void divisibility(struct divisible *stpr)
{
	char *str= stpr->p; //name the input as str
	int length=computeLength(str); // calculate the length of the input char array
	int sum=0;
	if(stpr->k%2==0) // if the number is repeated even number of times then Q is divisible by 11 
		printf("Divisible\n");// because then difference of sum of alternate numbers becomes zero 
	else // executes when the value of k is odd 
	{
		for(int index=0;index < length;index+=2)//calucate the sum of difference of consecutive numbers
		{
			if(length%2!=0 && index==length-1)
    	 		sum+= *(str+index)-'0';
   			else
     			sum+= *(str+index)- *(str+(index+1));
		}
		if(sum%11==0)//if the obtained sum is divisible by 11 then Q is divisible by 11
			printf("Divisible\n");
		else // Q is not divisible by 11
			printf("Not Divisible\n");
	}
}

int computeLength(char *str)
{
	int count=0;
	while(*str!='\0')
	{
		count++;
		str++;
	}
	return count;
}