/*Given the inputs P (string) and K then O is generated by replicating the P, K times.
 Check the divisibility of Q by 11 */
#include<stdio.h>
struct divisible
{
	char *p; //p is input char array
	int k; //k is no of times the number should be repeated to obtain Q
}d[]={
			{"123",3},
			{"123",1},
			{"5",3},
			{"5",8},
			{"123456789123456789123456789",9},
			{"12345678911234567891",6},
			{"12345678911234567891",5},
			{"12",100},
			{"0",14}
		};
void testCases();
int computeLength(char *str);
void divisibility(struct divisible *stpr);

int main(void)
{
	testCases();
	return 0;
}

void testCases()
{
	int noOfElements=sizeof(d)/sizeof(d[0]);
	for(int index=0;index<noOfElements;index++)
		divisibility(&d[index]);
}

void divisibility(struct divisible *stpr)
{
	char *str= stpr->p; //name the input as str
	int length=computeLength(str); // calculate the length of the input char array
	long int sum=0;
	for(int index=0;index<length;index++)//calculate the sum of all digits in p
		sum+= str[index]-'0';
	if(sum%3==0 || stpr->k%3==0) //if the sum of digits in p is divisible by 3 or if k is divisible by 3
		printf("Divisible\n");//then q is divisible by 3 because sum of the digits of q is (sum of digits of p * k)
	else
		printf("Not Divisible\n");
}

int computeLength(char *str)
{
	int count=0;
	while(str[count]!='\0')
	{
		count++;
	}
	return count;
}